name: Deploy to GitHub Pages

on:
    workflow_dispatch:  # This event allows the workflow to be manually triggered

jobs:
    build:
      strategy:
        matrix:
          idf_ver: ["latest"]
      runs-on: ubuntu-latest
      container: espressif/idf:${{ matrix.idf_ver }}
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            submodules: 'recursive'

        - name: Action for Building and Uploading Binaries
          uses: espressif/idf-examples-launchpad-ci-action@v1.0
          with:
            idf_version: ${{ matrix.idf_ver }}

        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: built_files
            path: binaries/

    deploy:
      needs: build

      permissions:
        pages: write      
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest
      steps:
        - name: Download built files
          uses: actions/download-artifact@v3
          with:
            name: built_files
            path: binaries/

        - name: Upload built files to gh pages
          uses: actions/upload-pages-artifact@v2
          with:
            path: binaries/

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
